[window]
padding = { x = 2, y = 2 }

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 11

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 500
unfocused_hollow = false

[scrolling]
history = 5000

[colors.primary]
background = '#101010'
foreground = '#ffffff'

[colors.normal]
black   = '#101010'
red     = '#f5a191'
green   = '#90b99f'
yellow  = '#e6b99d'
blue    = '#aca1cf'
magenta = '#e29eca'
cyan    = '#ea83a5'
white   = '#a0a0a0'

[colors.bright]
black   = '#7e7e7e'
red     = '#ff8080'
green   = '#99ffe4'
yellow  = '#ffc799'
blue    = '#b9aeda'
magenta = '#ecaad6'
cyan    = '#f591b2'
white   = '#ffffff'

[bell]
animation = "Linear"
duration = 0

[env]
TERM = "xterm-256color"
