#
include /home/alex/.config/kitty/kitty.falcon.conf
# BEGIN_KITTY_FONTS
font_family      family="Maple Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

disable_ligatures always
font_size 11
# adjust_column_width 1

scrollback_lines 5000

url_style single

background #171616
foreground #e2e0df
selection_background #353331
selection_foreground #e2e0df
url_color #96d8e3
cursor #eaa4c9
cursor_text_color #171616

# Tabs
active_tab_background #eaa4c9
active_tab_foreground #171616
inactive_tab_background #282625
inactive_tab_foreground #b1ada9
#tab_bar_background #100f0f

# Windows
active_border_color #966b81
inactive_border_color #454240

# normal
color0 #171616
color1 #e99696
color2 #98cdaa
color3 #dfd286
color4 #96bddf
color5 #eaa4c9
color6 #96d8e3
color7 #b1ada9

# bright
color8  #454240
color9  #f0b7b7
color10 #badec6
color11 #eee7c4
color12 #b5d0e8
color13 #eec4d9
color14 #c4e7ee
color15 #e2e0df

# extended colors
color16 #e3b096
color17 #cca6e7

repaint_delay 10
input_delay 3

sync_to_monitor yes

enable_audio_bell no

remember_window_size no

window_padding_width 2.0


cursor_shape block
cursor_blink yes
cursor_blink_interval 0.5
